version: '3.1'

services:
  springboot:
    build: ../images/springboot
    ports:
      - 8080:8080
     volumes:
       - springbootdata
     depends_on:
       - db
     link:
      - db
  db:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: amtdb
      MYSQL_ROOT_PASSWORD: root
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - 8888:80 

volumes:
  dbdata:
  springbootdata:
